#!/bin/sh
# ScreenStudio for GNU/Linux Launcher wrapper
# Copyright (C) 2008 Patrick Balleux <patrick.balleux@gmail.com>
# Copyright (C) 2013 PhobosK <phobosk@kbfx.net>
# Copyright (C) 2016 Karl Ellis <soylent.tv@gmail.com>
# Version 1.0

# Set the working directory
DIR=/usr/lib/ScreenStudio

# Run the application
cd $DIR
java -jar ScreenStudio.jar
