#!/bin/sh
# ScreenStudio for GNU/Linux Launcher wrapper
# Copyright (C) 2008 Patrick Balleux <patrick.balleux@gmail.com>
# Copyright (C) 2013 PhobosK <phobosk@kbfx.net>
# Copyright (C) 2016 Karl Ellis <soylent.tv@gmail.com>
# Version 1.0

# Set the working directory
INSTALLDIR=/usr/lib/screenstudio

# Run the application
cd ${INSTALLDIR}

java -cp ScreenStudio.jar:lib/* screenstudio.gui.Main
